### ISSUE TITLE
Performance tracking issue

### ISSUE THREAD

**Issue by vadixidav** [vadixidav/hwt#6]
Performance is currently only beating linear (which is incredibly fast on modern processors) for exact search at > 1M features. This is probably beatable, but it will require some optimizations. Below is the list of optimizations and their issues that need to be made:

- [ ] Use `packed_simd` to speed up `FeatureHeap::add`
- [ ] Implement more SIMD optimizations upstream in `swar`
- [ ] Investigate if the `search` module can be sped up using SIMD or bit twiddling
- [ ] Convert `search` module to use a hand-optimized iterator for each level of the tree

**Comment by vadixidav** [comment]
After closing #7 I am now getting the following:

```
neighbors/nearest_1_hwt_maxerr_0/16777216                        
                        time:   [17.479 ms 17.687 ms 17.849 ms]
```

This is a reasonable speedup over linear at `2^24` features.
